### ISSUE TITLE
Can't modify domain

### ISSUE THREAD

**Issue by Vineg** [boyers/hashpass#2]
I think it would be nice if you can easily change domain field. For example if you want to use your password to access subdomain of website.

**Comment by boyers** [comment]
Great suggestion. I'll leave this open until I find the time to do it. Until then, you can use this Python script:

```python
#!/usr/bin/python -O
import base64, getpass, hashlib

domain = raw_input('Domain: ').lower()
key = getpass.getpass('Key: ')

bits = domain + '/' + key
for i in range(2 ** 16):
  bits = hashlib.sha256(bits).digest()
password = base64.b64encode(bits)[:16]

print('Password: ' + password)
```

**Comment by adm244** [comment]
**Vineg**, I've made a necessary changes so that it's possible to modify domain name now and I've also created a pull request to merge those changes in this repository. For now you can grab a new version from my fork.

**Comment by boyers** [comment]
Resolved by https://github.com/boyers/hashpass/pull/3 and https://github.com/boyers/hashpass/commit/082d22e5899cbec919795140b853d51fd9428b42. Thanks @Vineg for the suggestion and @adm244 for the solution.
